<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>CloudSource.Playnite.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudSource.Playnite\CloudSource.Playnite.csproj" />
    <PackageReference Include="PlayniteSDK" Version="6.16.0" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
